### ISSUE TITLE
File Permissons

### ISSUE THREAD

**Issue by alexlinz** [McMahonLab/Scripts#1]
Permission denied when trying to delete items in input and output folders and when trying to copy to these folder
Solution: @sstevens2 will add me to ptools group

**Comment by sstevens2** [comment]
I added @alexlinz  to the ptools group on zissou.  
@alexlinz, please check that you have permissions now and if that works, close the issue.

**Comment by alexlinz** [comment]
Still not working. I'm trying to delete the following file:
/shared_software/metapathways2-2.5.2/input/AAA028K15.fna
using "rm"

This results in a prompt that asks:
rm: remove write-protected regular file ‘AAA028K15.fna’?
I type "y"
And get 
rm: cannot remove ‘AAA028K15.fna’: Permission denied

When trying to copy files from my home directory using the following command:
cp ../../../home/amlinz/C1genomes/*.fasta .
Each file gives the error:
cp: cannot create regular file ‘./Methylotenera_spL2L1.fasta’: Permission denied

**Comment by joshamilton** [comment]
Changed ownership of the following folders to ptools group:

/shared_software/metapathways2-2.5.2/input
/shared_software/metapathways2-2.5.2/output
/shared_software/metapathways2-2.5.2/config

@sstevens2 needs to change owner of `/shared_software/ptools-local/pgdbs/user` to ptools group.

@alexlinz, please try again and close the issue.

**Comment by sstevens2** [comment]
I changed the group of /shared_software/ptools-local and everything under
it to the ptools group.
Sarah

**Comment by alexlinz** [comment]
Almost there. I cannot delete the following directory:
shared_software/metapathways2-2.5.2/output/AAA028K15

Still getting that permission denied error. Can someone change the permissions on this directory?

**Comment by sstevens2** [comment]
Since that is owned by @joshamilton , I'll let him change it.

**Comment by joshamilton** [comment]
Changing permissions on individual output directories is not a viable long-term solution, as whomever last ran MP will have to change the permissions every time. I deleted the input and output files, and updated the MP protocol to require users to inform file owners to move their files.

**Comment by sstevens2** [comment]
Sounds like a better long term plan.

Although you can recursively change permissions and just add the group as owner.
Example:
'chgrp -R ptools /shared_software/metapathways2-2.5.2/output/AAA028K15'

**Comment by alexlinz** [comment]
Thanks both of you, everything seems to be working now!
